/**
 * Word + quote banks and the generators that turn a Mode into a target word list.
 */

export const WORD_BANK: readonly string[] = [
  "the", "of", "and", "to", "in", "a", "is", "that", "for", "it",
  "as", "was", "with", "be", "by", "on", "not", "he", "she", "they",
  "at", "this", "but", "from", "or", "have", "an", "them", "were", "we",
  "can", "there", "been", "has", "more", "if", "will", "would", "about", "which",
  "when", "one", "all", "their", "what", "so", "up", "out", "into", "than",
  "time", "just", "know", "take", "people", "year", "your", "good", "some", "could",
  "see", "other", "then", "now", "look", "only", "come", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "make", "world", "life", "hand", "part", "child", "eye", "woman", "place", "case",
  "point", "government", "company", "number", "group", "problem", "fact", "water", "money", "story",
  "month", "night", "home", "system", "program", "question", "school", "state", "family", "student",
  "country", "book", "word", "side", "head", "house", "service", "friend", "father", "power",
  "hour", "game", "line", "end", "member", "law", "car", "city", "name", "team",
  "minute", "idea", "kid", "body", "level", "office", "door", "health", "person", "art",
  "war", "history", "party", "result", "change", "morning", "reason", "research", "moment", "air",
  "teacher", "force", "education", "foot", "boy", "age", "policy", "process", "music", "market",
  "sense", "nation", "plan", "college", "interest", "death", "course", "someone", "experience", "behind",
  "field", "human", "space", "future", "value", "focus", "build", "design", "signal", "engine",
  "island", "silver", "shadow", "bright", "quiet", "stone", "river", "forest", "winter", "summer",
  "orbit", "planet", "matter", "energy", "motion", "circle", "square", "pattern", "layer", "simple",
  "modern", "strong", "light", "sharp", "smooth", "clear", "steady", "rapid", "gentle", "above",
  "across", "act", "active", "add", "admit", "adult", "afraid", "afternoon", "again", "against",
  "agree", "ahead", "allow", "almost", "alone", "along", "already", "although", "always", "among",
  "amount", "ancient", "anger", "angle", "animal", "answer", "anyone", "appear", "apple", "apply",
  "april", "area", "argue", "arm", "army", "around", "arrive", "arrow", "article", "artist",
  "ask", "asleep", "aspect", "assume", "attack", "attempt", "attend", "author", "autumn", "avoid",
  "awake", "aware", "away", "baby", "balance", "ball", "band", "bank", "bar", "base",
  "basket", "battle", "beach", "bear", "beat", "beauty", "become", "bed", "beer", "before",
  "begin", "behavior", "believe", "bell", "belong", "below", "bench", "beneath", "benefit", "best",
  "better", "between", "beyond", "bicycle", "big", "bill", "bird", "birth", "bit", "bite",
  "black", "blade", "blame", "blanket", "blind", "block", "blood", "blue", "board", "boat",
  "boil", "bold", "bone", "border", "born", "borrow", "both", "bottle", "bottom", "bounce",
  "bowl", "box", "brain", "branch", "brave", "bread", "break", "breath", "brick", "bridge",
  "brief", "bring", "broad", "broken", "brother", "brown", "brush", "bubble", "budget", "bug",
  "burn", "bury", "business", "busy", "butter", "button", "buy", "cabin", "cable", "cake",
  "calm", "camera", "camp", "canal", "cancel", "candle", "canvas", "capital", "captain", "capture",
  "card", "care", "career", "careful", "carry", "cast", "castle", "catch", "cattle", "cause",
  "cave", "ceiling", "cell", "center", "century", "certain", "chain", "chair", "chance", "channel",
  "chapter", "charge", "charm", "chart", "chase", "cheap", "check", "cheese", "chest", "chicken",
  "chief", "choice", "choose", "church", "circuit", "citizen", "civil", "claim", "class", "clean",
  "clever", "click", "cliff", "climb", "clock", "close", "cloth", "cloud", "club", "coach",
  "coal", "coast", "coat", "code", "coffee", "coin", "cold", "collect", "color", "column",
  "combine", "comfort", "command", "comment", "common", "compare", "compete", "complex", "concept", "concern",
  "concert", "conduct", "confirm", "connect", "consider", "constant", "contact", "contain", "content", "contest",
  "context", "continue", "contract", "control", "convert", "cook", "cool", "copper", "copy", "corner",
  "correct", "cost", "cotton", "count", "couple", "courage", "cover", "crack", "craft", "crash",
  "crazy", "cream", "create", "credit", "crew", "crime", "crisis", "critic", "crop", "cross",
  "crowd", "crown", "cruel", "crush", "cry", "crystal", "culture", "cup", "curious", "current",
  "curve", "custom", "cut", "cycle", "damage", "dance", "danger", "dark", "data", "date",
  "daughter", "dawn", "deal", "dear", "debate", "debt", "decade", "decide", "declare", "deep",
  "defeat", "defend", "define", "degree", "delay", "deliver", "demand", "deny", "depend", "depth",
  "describe", "desert", "deserve", "desire", "despite", "destroy", "detail", "detect", "develop", "device",
  "devote", "diamond", "diary", "differ", "digital", "dinner", "direct", "dirt", "disagree", "discuss",
  "disease", "dish", "dismiss", "distance", "divide", "doctor", "document", "dog", "dollar", "domain",
  "dominant", "donate", "double", "doubt", "draft", "drag", "drama", "draw", "dream", "dress",
  "drink", "drive", "drop", "drum", "dry", "duck", "due", "dust", "duty", "each",
  "eager", "early", "earn", "earth", "ease", "east", "easy", "echo", "edge", "edit",
  "effect", "effort", "either", "elbow", "elect", "element", "else", "emerge", "emotion", "employ",
  "empty", "enable", "enemy", "engage", "enjoy", "enough", "enter", "entire", "entry", "equal",
  "equip", "error", "escape", "essay", "estate", "eternal", "event", "ever", "every", "exact",
  "exam", "example", "except", "exchange", "excite", "excuse", "exist", "exit", "expand", "expect",
  "expert", "explain", "explore", "export", "expose", "express", "extend", "extra", "extreme", "fabric",
  "face", "factor", "fail", "fair", "faith", "fall", "false", "fame", "famous", "fancy",
  "far", "farm", "fashion", "fast", "fate", "favor", "fear", "feather", "feature", "federal",
  "feed", "feel", "fellow", "female", "fence", "festival", "fetch", "fever", "few", "fiber",
  "fiction", "fight", "figure", "file", "fill", "film", "final", "finance", "find", "fine",
  "finger", "finish", "fire", "firm", "fish", "fit", "fix", "flag", "flame", "flash",
  "flat", "flavor", "flee", "flight", "float", "flood", "floor", "flour", "flow", "flower",
  "fluid", "fly", "fold", "follow", "food", "fool", "forbid", "forecast", "foreign", "forget",
  "forgive", "fork", "form", "formal", "format", "former", "fortune", "forward", "fossil", "found",
  "fountain", "frame", "free", "freeze", "fresh", "fried", "friendly", "frog", "front", "frozen",
  "fruit", "fuel", "full", "fun", "function", "fund", "funny", "furniture", "gain", "gallery",
  "gap", "garage", "garden", "gate", "gather", "gear", "general", "generous", "genius", "genuine",
  "gesture", "ghost", "giant", "gift", "girl", "glad", "glass", "global", "globe", "glory",
  "glove", "glow", "goal", "goat", "gold", "golf", "govern", "grab", "grace", "grade",
  "grain", "grand", "grant", "grape", "grasp", "grass", "grave", "gray", "great", "green",
  "greet", "grid", "grief", "grill", "grip", "grocery", "ground", "grow", "guard", "guess",
  "guest", "guide", "guilt", "guitar", "gun", "habit", "hair", "half", "hall", "halt",
  "hammer", "handle", "hang", "happen", "happy", "harbor", "hard", "harm", "harvest", "hat",
  "hate", "haunt", "hazard", "heal", "heart", "heat", "heaven", "heavy", "hedge", "height",
  "hello", "helmet", "help", "herb", "hero", "hidden", "hide", "high", "hill", "hint",
  "hire", "hit", "hobby", "hold", "hole", "holiday", "hollow", "holy", "honest", "honey",
  "honor", "hope", "horizon", "horn", "horse", "hospital", "host", "hot", "hotel", "however",
  "huge", "humble", "humor", "hundred", "hungry", "hunt", "hurry", "hurt", "husband", "hybrid",
  "ice", "icon", "ideal", "identify", "idle", "ignore", "ill", "image", "imagine", "impact",
  "imply", "import", "impose", "impress", "improve", "impulse", "inch", "include", "income", "increase",
  "indeed", "index", "indicate", "indoor", "industry", "infant", "inform", "initial", "injury", "inner",
  "innocent", "input", "inquiry", "insect", "inside", "insist", "inspire", "install", "instant", "instead",
  "insult", "intend", "intense", "invent", "invest", "invite", "involve", "iron", "issue", "item",
  "jacket", "jail", "jar", "jazz", "jealous", "jeans", "jelly", "jewel", "job", "join",
  "joke", "journal", "journey", "joy", "judge", "juice", "jump", "jungle", "junior", "jury",
  "justice", "keen", "keep", "key", "kick", "kind", "king", "kiss", "kitchen", "knee",
  "knife", "knock", "knot", "knowledge", "label", "labor", "lack", "lake", "lamp", "land",
  "language", "large", "last", "late", "laugh", "launch", "laundry", "lava", "lazy", "lead",
  "leaf", "league", "lean", "learn", "lease", "least", "leather", "leave", "lecture", "left",
  "leg", "legal", "legend", "lemon", "lend", "length", "lens", "less", "lesson", "letter",
  "liberty", "library", "license", "lie", "lift", "likely", "limb", "limit", "link", "lion",
  "liquid", "list", "listen", "little", "live", "load", "loan", "local", "lock", "logic",
  "lonely", "long", "loop", "lose", "loss", "lost", "loud", "love", "low", "loyal",
  "luck", "lunch", "lung", "luxury", "machine", "mad", "magic", "magnet", "mail", "main",
  "maintain", "major", "mall", "manage", "manner", "manual", "many", "map", "marble", "march",
  "margin", "marine", "mark", "marriage", "mask", "mass", "master", "match", "material", "math",
  "maximum", "maybe", "mayor", "meal", "mean", "measure", "meat", "media", "medical", "medium",
  "meet", "melody", "melt", "memory", "mention", "menu", "mercy", "mere", "merge", "merit",
  "message", "metal", "method", "middle", "might", "mild", "mile", "milk", "mill", "mind",
  "mine", "mineral", "minor", "mirror", "miss", "mission", "mistake", "mix", "mobile", "model",
  "modest", "modify", "monitor", "monkey", "mood", "moon", "moral", "mother", "motor", "mount",
  "mountain", "mouse", "mouth", "move", "movie", "mud", "multiply", "murder", "muscle", "museum",
  "mushroom", "must", "mutual", "mystery", "myth", "nail", "naked", "narrow", "nasty", "native",
  "natural", "nature", "near", "neat", "neck", "need", "needle", "negative", "neighbor", "neither",
  "nerve", "nest", "net", "network", "neutral", "never", "news", "next", "nice", "niece",
  "nine", "noble", "nobody", "nod", "noise", "none", "noon", "normal", "north", "nose",
  "note", "nothing", "notice", "novel", "nowhere", "nuclear", "nurse", "nut", "oak", "obey",
  "object", "oblige", "observe", "obtain", "obvious", "occasion", "occupy", "occur", "ocean", "odd",
  "offer", "often", "oil", "okay", "old", "olive", "once", "onion", "online", "open",
  "opera", "opinion", "oppose", "option", "orange", "orchard", "order", "ordinary", "organ", "origin",
  "ought", "ounce", "outer", "outline", "output", "outside", "oven", "overcome", "owe", "own",
  "owner", "oxygen", "pace", "pack", "page", "pain", "paint", "pair", "palace", "pale",
  "palm", "panel", "panic", "paper", "parade", "parent", "park", "parking", "parrot", "passage",
  "passion", "past", "patch", "path", "patience", "patient", "pause", "pave", "payment", "peace",
  "peak", "pearl", "peculiar", "pen", "pencil", "pepper", "percent", "perfect", "perform", "perhaps",
  "period", "permit", "pet", "phase", "phone", "photo", "phrase", "physical", "piano", "pick",
  "picture", "piece", "pile", "pilot", "pin", "pink", "pioneer", "pipe", "pitch", "pity",
  "pizza", "plain", "plane", "plant", "plastic", "plate", "play", "pleasant", "please", "pledge",
  "plenty", "plot", "plug", "plunge", "pocket", "poem", "poet", "poison", "pole", "police",
  "polish", "polite", "pool", "poor", "pop", "popular", "port", "portion", "portrait", "position",
  "positive", "possess", "possible", "post", "pot", "potato", "pound", "pour", "poverty", "powder",
  "practice", "praise", "pray", "precise", "predict", "prefer", "prepare", "present", "preserve", "press",
  "pretend", "pretty", "prevent", "previous", "price", "pride", "primary", "prime", "print", "prior",
  "prison", "private", "prize", "probable", "produce", "product", "profile", "profit", "project", "promise",
  "promote", "prompt", "proof", "proper", "propose", "protect", "proud", "prove", "provide", "public",
  "publish", "pull", "pulse", "pump", "punch", "punish", "pupil", "purchase", "pure", "purple",
  "purpose", "pursue", "push", "puzzle", "quality", "quantity", "quarter", "queen", "quest", "quick",
  "quit", "quite", "quote", "race", "radio", "rail", "rain", "raise", "rally", "random",
  "range", "rank", "rare", "rate", "rather", "ratio", "raw", "reach", "react", "read",
  "ready", "real", "realize", "rear", "rebel", "recall", "receive", "recent", "recipe", "record",
  "recover", "recruit", "reduce", "refer", "reflect", "reform", "refuse", "regard", "region", "register",
  "regret", "regular", "reject", "relate", "relax", "release", "relief", "rely", "remain", "remark",
  "remember", "remind", "remove", "render", "renew", "rent", "repair", "repeat", "replace", "reply",
  "report", "represent", "request", "require", "rescue", "resist", "resolve", "resource", "respect", "respond",
  "rest", "restore", "retain", "retire", "retreat", "return", "reveal", "reverse", "review", "revise",
  "reward", "rhythm", "rice", "rich", "ride", "ridge", "rifle", "right", "rigid", "ring",
  "rise", "risk", "ritual", "rival", "road", "roast", "rock", "rocket", "role", "roll",
  "roof", "room", "root", "rope", "rose", "rough", "round", "route", "routine", "row",
  "royal", "rubber", "rude", "rug", "rule", "rumor", "run", "rural", "rush", "sacred",
  "sad", "safe", "sail", "salad", "salary", "sale", "salt", "sample", "sand", "satellite",
  "satisfy", "sauce", "save", "say", "scale", "scan", "scar", "scene", "schedule", "scheme",
  "science", "scissors", "scope", "score", "scratch", "scream", "screen", "script", "sea", "search",
  "season", "seat", "second", "secret", "section", "secure", "seed", "seek", "seem", "seize",
  "seldom", "select", "self", "sell", "senate", "send", "senior", "sentence", "separate", "series",
  "serious", "serve", "session", "settle", "seven", "several", "severe", "shade", "shake", "shall",
  "shallow", "shame", "shape", "share", "shark", "shed", "sheep", "sheet", "shelf", "shell",
  "shelter", "shield", "shift", "shine", "ship", "shirt", "shock", "shoe", "shoot", "shop",
  "shore", "short", "shot", "should", "shoulder", "shout", "show", "shower", "shrink", "shut",
  "shy", "sick", "sign", "silence", "silk", "silly", "similar", "since", "sing", "single",
  "sink", "sister", "sit", "site", "situation", "size", "skill", "skin", "skirt", "sky",
  "slave", "sleep", "slice", "slide", "slight", "slip", "slope", "slow", "small", "smart",
  "smell", "smile", "smoke", "snake", "snow", "soap", "social", "society", "sock", "soft",
  "soil", "solar", "soldier", "solid", "solve", "son", "song", "soon", "sorry", "sort",
  "soul", "sound", "soup", "source", "south", "spare", "spark", "speak", "special", "species",
  "specific", "speech", "speed", "spell", "spend", "sphere", "spice", "spin", "spirit", "split",
  "spoke", "spoon", "sport", "spot", "spread", "spring", "squeeze", "stable", "staff", "stage",
  "stair", "stake", "stamp", "stand", "standard", "star", "stare", "start", "starve", "station",
  "stay", "steal", "steam", "steel", "steep", "steer", "stem", "step", "stick", "stiff",
  "still", "stir", "stock", "stomach", "storm", "straight", "strain", "strange", "stream", "street",
  "stress", "stretch", "strict", "strike", "string", "strip", "stripe", "stroke", "struggle", "study",
  "stuff", "stupid", "style", "subject", "submit", "succeed", "such", "sudden", "suffer", "sugar",
  "suggest", "suit", "summit", "sun", "super", "supply", "support", "suppose", "sure", "surface",
  "surgery", "surprise", "surround", "survey", "survive", "suspect", "sustain", "swallow", "swear", "sweep",
  "sweet", "swim", "swing", "switch", "sword", "symbol", "table", "tail", "talent", "talk",
  "tall", "tank", "tape", "target", "task", "taste", "tax", "tea", "teach", "tear",
  "tech", "tell", "temper", "temple", "tend", "tender", "tennis", "tension", "tent", "term",
  "terrible", "test", "text", "thank", "theme", "theory", "therapy", "therefore", "thick", "thin",
  "thing", "third", "thirty", "thought", "thread", "threat", "three", "throat", "throw", "thumb",
  "thunder", "thus", "ticket", "tide", "tie", "tiger", "tight", "timber", "tiny", "tip",
  "tired", "tissue", "title", "toast", "today", "toe", "together", "tomato", "tomorrow", "tone",
  "tongue", "tonight", "tool", "tooth", "top", "topic", "torch", "total", "touch", "tough",
  "tour", "toward", "tower", "town", "toy", "trace", "track", "trade", "tradition", "traffic",
  "trail", "train", "trait", "transfer", "transit", "trap", "travel", "tray", "treat", "tree",
  "trend", "trial", "tribe", "trick", "trip", "trophy", "trouble", "truck", "true", "trust",
  "truth", "try", "tube", "tune", "tunnel", "turn", "twelve", "twenty", "twice", "twin",
  "twist", "type", "typical", "ugly", "ultimate", "umbrella", "unable", "uncle", "under", "undergo",
  "understand", "unfair", "uniform", "union", "unique", "unit", "unite", "universe", "unknown", "unless",
  "unlike", "until", "unusual", "update", "upon", "upper", "upset", "urban", "urge", "urgent",
  "usual", "utility", "vacant", "vacation", "valley", "valuable", "van", "vanish", "variety", "various",
  "vast", "vegetable", "vehicle", "venture", "verb", "version", "vessel", "veteran", "victim", "victory",
  "video", "view", "village", "violence", "violin", "virtue", "virus", "visible", "vision", "visit",
  "vital", "vivid", "vocal", "voice", "volume", "vote", "voyage", "wage", "wagon", "wait",
  "wake", "walk", "wall", "wander", "warm", "warn", "warrior", "wash", "waste", "watch",
  "wave", "weak", "wealth", "weapon", "wear", "weather", "web", "wedding", "week", "weight",
  "weird", "welcome", "west", "wet", "whale", "wheat", "wheel", "where", "whether", "while",
  "whisper", "whistle", "white", "whole", "whom", "whose", "wide", "widow", "width", "wife",
  "wild", "win", "wind", "window", "wine", "wing", "winner", "wipe", "wire", "wisdom",
  "wise", "wish", "witness", "wolf", "wonder", "wood", "wool", "worry", "worse", "worship",
  "worth", "wound", "wrap", "wrist", "write", "wrong", "yard", "yellow", "yes", "yesterday",
  "yet", "yield", "young", "youth", "zero", "zone", "algorithm", "array", "async", "await",
  "backup", "bandwidth", "binary", "boolean", "buffer", "cache", "callback", "client", "cluster", "commit",
  "compile", "compiler", "component", "config", "console", "container", "cookie", "cursor", "daemon", "database",
  "debug", "decode", "default", "delete", "deploy", "deprecate", "diff", "directory", "disk", "display",
  "driver", "editor", "encode", "endpoint", "entity", "exception", "execute", "filter", "firewall", "folder",
  "framework", "gateway", "handler", "hardware", "hash", "header", "heap", "inherit", "instance", "integer",
  "interface", "iterate", "kernel", "keyboard", "keyword", "latency", "legacy", "linker", "literal", "loader",
  "login", "macro", "migrate", "module", "mutex", "namespace", "node", "null", "offset", "operator",
  "package", "packet", "parameter", "parse", "partition", "password", "payload", "pipeline", "pixel", "plugin",
  "pointer", "prefix", "printer", "property", "protocol", "proxy", "query", "queue", "recursion", "refactor",
  "reference", "remote", "repository", "response", "router", "runtime", "scalar", "schema", "sector", "segment",
  "semantic", "sensor", "serial", "server", "socket", "software", "solution", "stack", "static", "storage",
  "struct", "subnet", "suffix", "syntax", "template", "terminal", "throughput", "timeout", "token", "toolkit",
  "transaction", "transform", "trigger", "tuple", "unicode", "upgrade", "upload", "user", "validate", "variable",
  "vector", "virtual", "warning", "widget", "wrapper",
];

export type QuoteLength = "short" | "medium" | "long";

export type Quote = {
  text: string;
  author: string;
  length: QuoteLength;
};

export const QUOTES: readonly Quote[] = [
  {
    text: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
    length: "short",
  },
  {
    text: "The best way to predict the future is to invent it.",
    author: "Alan Kay",
    length: "short",
  },
  {
    text: "Talk is cheap. Show me the code.",
    author: "Linus Torvalds",
    length: "short",
  },
  {
    text: "Any sufficiently advanced technology is indistinguishable from magic.",
    author: "Arthur C. Clarke",
    length: "short",
  },
  {
    text: "Programs must be written for people to read, and only incidentally for machines to execute. The elegance of a program lies in how clearly it explains itself.",
    author: "Harold Abelson",
    length: "medium",
  },
  {
    text: "The function of good software is to make the complex appear to be simple. A designer knows they have achieved perfection not when there is nothing left to add, but when there is nothing left to take away.",
    author: "Grady Booch",
    length: "medium",
  },
  {
    text: "We are stuck with technology when what we really want is just stuff that works. The measure of a system is not how clever it is, but how little it demands of the person using it.",
    author: "Douglas Adams",
    length: "medium",
  },
  {
    text: "Controlling complexity is the essence of computer programming. The problems we face are rarely a shortage of processing power or memory. They are almost always a shortage of clarity, of shared understanding, of the patience required to name things well and to draw the boundaries between them in a way that a stranger could follow six months later without asking a single question.",
    author: "Brian Kernighan",
    length: "long",
  },
  {
    text: "The most important property of a program is whether it accomplishes the intention of its user. Everything else follows from that. A fast program that returns the wrong answer is worthless, an elegant program nobody can run is a curiosity, and a clever program that only its author can maintain is a liability disguised as an achievement.",
    author: "C. A. R. Hoare",
    length: "long",
  },
  {
    text: "There are two ways of constructing a software design. One way is to make it so simple that there are obviously no deficiencies. The other way is to make it so complicated that there are no obvious deficiencies. The first method is far more difficult, and it is the one worth practicing every single day of your working life.",
    author: "C. A. R. Hoare",
    length: "long",
  },
  {
    text: "Premature optimization is the root of all evil.",
    author: "Donald Knuth",
    length: "short",
  },
  {
    text: "Beware of bugs in the above code; I have only proved it correct, not tried it.",
    author: "Donald Knuth",
    length: "short",
  },
  {
    text: "Perfection is achieved when there is nothing left to take away.",
    author: "Antoine de Saint-Exupery",
    length: "short",
  },
  {
    text: "First, solve the problem. Then, write the code.",
    author: "John Johnson",
    length: "short",
  },
  {
    text: "Make it work, make it right, make it fast.",
    author: "Kent Beck",
    length: "short",
  },
  {
    text: "Walking on water and developing software from a specification are easy if both are frozen.",
    author: "Edward Berard",
    length: "short",
  },
  {
    text: "The computer was born to solve problems that did not exist before.",
    author: "Bill Gates",
    length: "short",
  },
  {
    text: "Software is a great combination of artistry and engineering.",
    author: "Bill Gates",
    length: "short",
  },
  {
    text: "Debugging is twice as hard as writing the code in the first place.",
    author: "Brian Kernighan",
    length: "short",
  },
  {
    text: "Testing shows the presence, not the absence of bugs.",
    author: "Edsger Dijkstra",
    length: "short",
  },
  {
    text: "Simplicity is prerequisite for reliability.",
    author: "Edsger Dijkstra",
    length: "short",
  },
  {
    text: "The question of whether machines can think is about as relevant as whether submarines can swim.",
    author: "Edsger Dijkstra",
    length: "short",
  },
  {
    text: "If you think it is expensive to hire a professional, wait until you hire an amateur.",
    author: "Red Adair",
    length: "short",
  },
  {
    text: "Science is what we understand well enough to explain to a computer.",
    author: "Donald Knuth",
    length: "short",
  },
  {
    text: "Everything should be made as simple as possible, but not simpler.",
    author: "Albert Einstein",
    length: "short",
  },
  {
    text: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    length: "short",
  },
  {
    text: "I have not failed. I have just found ten thousand ways that will not work.",
    author: "Thomas Edison",
    length: "short",
  },
  {
    text: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    author: "Thomas Edison",
    length: "short",
  },
  {
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    length: "short",
  },
  {
    text: "Design is not just what it looks like. Design is how it works.",
    author: "Steve Jobs",
    length: "short",
  },
  {
    text: "Stay hungry. Stay foolish.",
    author: "Steve Jobs",
    length: "short",
  },
  {
    text: "Real artists ship.",
    author: "Steve Jobs",
    length: "short",
  },
  {
    text: "An investment in knowledge pays the best interest.",
    author: "Benjamin Franklin",
    length: "short",
  },
  {
    text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    author: "Benjamin Franklin",
    length: "short",
  },
  {
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    length: "short",
  },
  {
    text: "I know that I know nothing.",
    author: "Socrates",
    length: "short",
  },
  {
    text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author: "Will Durant",
    length: "short",
  },
  {
    text: "The journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    length: "short",
  },
  {
    text: "Knowing yourself is the beginning of all wisdom.",
    author: "Aristotle",
    length: "short",
  },
  {
    text: "It always seems impossible until it is done.",
    author: "Nelson Mandela",
    length: "short",
  },
  {
    text: "In the middle of difficulty lies opportunity.",
    author: "Albert Einstein",
    length: "short",
  },
  {
    text: "Whether you think you can or you think you cannot, you are right.",
    author: "Henry Ford",
    length: "short",
  },
  {
    text: "Quality is not an act, it is a habit.",
    author: "Aristotle",
    length: "short",
  },
  {
    text: "Nothing in life is to be feared, it is only to be understood.",
    author: "Marie Curie",
    length: "short",
  },
  {
    text: "The best time to plant a tree was twenty years ago. The second best time is now.",
    author: "Chinese Proverb",
    length: "short",
  },
  {
    text: "Fall seven times, stand up eight.",
    author: "Japanese Proverb",
    length: "short",
  },
  {
    text: "Be the change that you wish to see in the world.",
    author: "Mahatma Gandhi",
    length: "short",
  },
  {
    text: "A room without books is like a body without a soul.",
    author: "Cicero",
    length: "short",
  },
  {
    text: "Not all those who wander are lost.",
    author: "J. R. R. Tolkien",
    length: "short",
  },
  {
    text: "All we have to decide is what to do with the time that is given us.",
    author: "J. R. R. Tolkien",
    length: "short",
  },
  {
    text: "It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife.",
    author: "Jane Austen",
    length: "short",
  },
  {
    text: "Call me Ishmael.",
    author: "Herman Melville",
    length: "short",
  },
  {
    text: "The past is never dead. It is not even past.",
    author: "William Faulkner",
    length: "short",
  },
  {
    text: "So we beat on, boats against the current, borne back ceaselessly into the past.",
    author: "F. Scott Fitzgerald",
    length: "short",
  },
  {
    text: "Do I dare disturb the universe?",
    author: "T. S. Eliot",
    length: "short",
  },
  {
    text: "Two roads diverged in a wood, and I took the one less traveled by.",
    author: "Robert Frost",
    length: "short",
  },
  {
    text: "The woods are lovely, dark and deep, but I have promises to keep.",
    author: "Robert Frost",
    length: "short",
  },
  {
    text: "Hope is the thing with feathers that perches in the soul.",
    author: "Emily Dickinson",
    length: "short",
  },
  {
    text: "I celebrate myself, and sing myself.",
    author: "Walt Whitman",
    length: "short",
  },
  {
    text: "Beauty is truth, truth beauty. That is all ye know on earth, and all ye need to know.",
    author: "John Keats",
    length: "short",
  },
  {
    text: "The child is father of the man.",
    author: "William Wordsworth",
    length: "short",
  },
  {
    text: "To be, or not to be, that is the question.",
    author: "William Shakespeare",
    length: "short",
  },
  {
    text: "All the world is a stage, and all the men and women merely players.",
    author: "William Shakespeare",
    length: "short",
  },
  {
    text: "We know what we are, but know not what we may be.",
    author: "William Shakespeare",
    length: "short",
  },
  {
    text: "The fault, dear Brutus, is not in our stars, but in ourselves.",
    author: "William Shakespeare",
    length: "short",
  },
  {
    text: "Somewhere, something incredible is waiting to be known.",
    author: "Carl Sagan",
    length: "short",
  },
  {
    text: "Extraordinary claims require extraordinary evidence.",
    author: "Carl Sagan",
    length: "short",
  },
  {
    text: "We are made of star stuff.",
    author: "Carl Sagan",
    length: "short",
  },
  {
    text: "Look up at the stars and not down at your feet.",
    author: "Stephen Hawking",
    length: "short",
  },
  {
    text: "Intelligence is the ability to adapt to change.",
    author: "Stephen Hawking",
    length: "short",
  },
  {
    text: "The important thing is not to stop questioning.",
    author: "Albert Einstein",
    length: "short",
  },
  {
    text: "Nature uses only the longest threads to weave her patterns.",
    author: "Richard Feynman",
    length: "short",
  },
  {
    text: "The first principle is that you must not fool yourself, and you are the easiest person to fool.",
    author: "Richard Feynman",
    length: "short",
  },
  {
    text: "What I cannot create, I do not understand.",
    author: "Richard Feynman",
    length: "short",
  },
  {
    text: "If I have seen further, it is by standing on the shoulders of giants.",
    author: "Isaac Newton",
    length: "short",
  },
  {
    text: "In the beginner's mind there are many possibilities, in the expert's there are few.",
    author: "Shunryu Suzuki",
    length: "short",
  },
  {
    text: "The map is not the territory.",
    author: "Alfred Korzybski",
    length: "short",
  },
  {
    text: "All models are wrong, but some are useful.",
    author: "George Box",
    length: "short",
  },
  {
    text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    author: "Martin Fowler",
    length: "short",
  },
  {
    text: "Programming is the art of telling another human what one wants the computer to do.",
    author: "Donald Knuth",
    length: "short",
  },
  {
    text: "A language that does not affect the way you think about programming is not worth knowing.",
    author: "Alan Perlis",
    length: "short",
  },
  {
    text: "Fools ignore complexity. Pragmatists suffer it. Geniuses remove it.",
    author: "Alan Perlis",
    length: "short",
  },
  {
    text: "Deleted code is debugged code.",
    author: "Jeff Sickel",
    length: "short",
  },
  {
    text: "Weeks of coding can save you hours of planning.",
    author: "Unknown",
    length: "short",
  },
  {
    text: "There are only two hard things in computer science: cache invalidation and naming things.",
    author: "Phil Karlton",
    length: "short",
  },
  {
    text: "Given enough eyeballs, all bugs are shallow.",
    author: "Eric S. Raymond",
    length: "short",
  },
  {
    text: "Every good work of software starts by scratching a developer's personal itch.",
    author: "Eric S. Raymond",
    length: "short",
  },
  {
    text: "Programs are meant to be read by humans and only incidentally for computers to execute.",
    author: "Donald Knuth",
    length: "short",
  },
  {
    text: "The cheapest, fastest, and most reliable components are those that are not there.",
    author: "Gordon Bell",
    length: "short",
  },
  {
    text: "When in doubt, use brute force.",
    author: "Ken Thompson",
    length: "short",
  },
  {
    text: "One of my most productive days was throwing away one thousand lines of code.",
    author: "Ken Thompson",
    length: "short",
  },
  {
    text: "Controlling complexity is the essence of computer programming.",
    author: "Brian Kernighan",
    length: "short",
  },
  {
    text: "Do not communicate by sharing memory, share memory by communicating.",
    author: "Rob Pike",
    length: "short",
  },
  {
    text: "Data dominates. If you have chosen the right data structures, the algorithms will be obvious.",
    author: "Rob Pike",
    length: "short",
  },
  {
    text: "Measure. Do not tune for speed until you have measured.",
    author: "Rob Pike",
    length: "short",
  },
  {
    text: "Good programmers worry about data structures and their relationships.",
    author: "Linus Torvalds",
    length: "short",
  },
  {
    text: "Given a choice between doing something and nothing, choose to do something.",
    author: "Theodore Roosevelt",
    length: "short",
  },
  {
    text: "Comparison is the thief of joy.",
    author: "Theodore Roosevelt",
    length: "short",
  },
  {
    text: "Do what you can, with what you have, where you are.",
    author: "Theodore Roosevelt",
    length: "short",
  },
  {
    text: "Courage is not the absence of fear, but the triumph over it.",
    author: "Nelson Mandela",
    length: "short",
  },
  {
    text: "Education is the most powerful weapon which you can use to change the world.",
    author: "Nelson Mandela",
    length: "short",
  },
  {
    text: "The only thing we have to fear is fear itself.",
    author: "Franklin D. Roosevelt",
    length: "short",
  },
  {
    text: "Ask not what your country can do for you, ask what you can do for your country.",
    author: "John F. Kennedy",
    length: "short",
  },
  {
    text: "Well done is better than well said.",
    author: "Benjamin Franklin",
    length: "short",
  },
  {
    text: "Time is the most valuable thing a man can spend.",
    author: "Theophrastus",
    length: "short",
  },
  {
    text: "A journey is best measured in friends rather than miles.",
    author: "Tim Cahill",
    length: "short",
  },
  {
    text: "The obstacle is the way.",
    author: "Marcus Aurelius",
    length: "short",
  },
  {
    text: "You have power over your mind, not outside events. Realize this, and you will find strength.",
    author: "Marcus Aurelius",
    length: "short",
  },
  {
    text: "Waste no more time arguing what a good man should be. Be one.",
    author: "Marcus Aurelius",
    length: "short",
  },
  {
    text: "We suffer more often in imagination than in reality.",
    author: "Seneca",
    length: "short",
  },
  {
    text: "Luck is what happens when preparation meets opportunity.",
    author: "Seneca",
    length: "short",
  },
  {
    text: "It is not that we have a short time to live, but that we waste much of it.",
    author: "Seneca",
    length: "short",
  },
  {
    text: "No man ever steps in the same river twice.",
    author: "Heraclitus",
    length: "short",
  },
  {
    text: "The only constant in life is change.",
    author: "Heraclitus",
    length: "short",
  },
  {
    text: "The most damaging phrase in the language is: we have always done it this way. Progress belongs to the people who are willing to try what has not been tried, and who are patient enough to keep trying after the first attempt fails.",
    author: "Grace Hopper",
    length: "medium",
  },
  {
    text: "A ship in port is safe, but that is not what ships are built for. Sail out to sea and do new things. The most important thing I have accomplished, other than building the compiler, is training young people.",
    author: "Grace Hopper",
    length: "medium",
  },
  {
    text: "It is easier to ask forgiveness than it is to get permission. Humans are allergic to change, and they love to say we have always done it this way, which is why I keep a clock on my wall that runs counterclockwise.",
    author: "Grace Hopper",
    length: "medium",
  },
  {
    text: "The purpose of computing is insight, not numbers. A calculation that produces an answer nobody understands has failed at the only task that mattered, no matter how many digits of precision it carries after the decimal point.",
    author: "Richard Hamming",
    length: "medium",
  },
  {
    text: "If you do not work on important problems, you cannot expect to do important work. The people who do great work are not necessarily smarter, but they have the courage to keep an open door and to think about what matters.",
    author: "Richard Hamming",
    length: "medium",
  },
  {
    text: "The real problem is not whether machines think but whether men do. We have built devices of extraordinary capability and then asked far too little of ourselves in the way of judgment about what to point them at.",
    author: "B. F. Skinner",
    length: "medium",
  },
  {
    text: "Any sufficiently advanced technology is indistinguishable from magic. When a distinguished but elderly scientist states that something is possible, he is almost certainly right; when he states that something is impossible, he is very probably wrong.",
    author: "Arthur C. Clarke",
    length: "medium",
  },
  {
    text: "The only way of discovering the limits of the possible is to venture a little way past them into the impossible. Every revolutionary idea seems to pass through three stages, and the last one is that we knew it was a good idea all along.",
    author: "Arthur C. Clarke",
    length: "medium",
  },
  {
    text: "It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change. From so simple a beginning, endless forms most beautiful and most wonderful have been, and are being, evolved.",
    author: "Charles Darwin",
    length: "medium",
  },
  {
    text: "Somewhere, something incredible is waiting to be known. We are a way for the cosmos to know itself, and every atom in our bodies was forged in the interior of a collapsing star long before the earth had a name.",
    author: "Carl Sagan",
    length: "medium",
  },
  {
    text: "Science is not only compatible with spirituality, it is a profound source of spirituality. Our species needs, and deserves, a citizenry with minds wide awake and a basic understanding of how the world works.",
    author: "Carl Sagan",
    length: "medium",
  },
  {
    text: "Books are the plane, and the train, and the road. They are the destination and the journey. They are home. When you read a great book, you become the person who read it, and you cannot become that person any other way.",
    author: "Anna Quindlen",
    length: "medium",
  },
  {
    text: "There is no friend as loyal as a book, and no thief as patient as the years. Read what pleases you, and read it slowly enough to argue with it, because a book you never disagree with has taught you nothing at all.",
    author: "Ernest Hemingway",
    length: "medium",
  },
  {
    text: "I would rather have a mind opened by wonder than one closed by belief. The moment you are certain, you have stopped looking, and everything interesting in this world lives just past the edge of what you already accept.",
    author: "Gerry Spence",
    length: "medium",
  },
  {
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall. There is no passion to be found in playing small, in settling for a life that is less than the one you are capable of living.",
    author: "Nelson Mandela",
    length: "medium",
  },
  {
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts. If you are going through hell, keep going, and never let the perfect become the enemy of what is merely very good and shipped on time.",
    author: "Winston Churchill",
    length: "medium",
  },
  {
    text: "Twenty years from now you will be more disappointed by the things you did not do than by the ones you did do. So throw off the bowlines, sail away from the safe harbor, catch the trade winds in your sails. Explore. Dream. Discover.",
    author: "H. Jackson Brown Jr.",
    length: "medium",
  },
  {
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail. To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment there is.",
    author: "Ralph Waldo Emerson",
    length: "medium",
  },
  {
    text: "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.",
    author: "Henry David Thoreau",
    length: "medium",
  },
  {
    text: "Our life is frittered away by detail. Simplify, simplify. Instead of three meals a day, if it be necessary eat but one; instead of a hundred dishes, five; and reduce other things in proportion.",
    author: "Henry David Thoreau",
    length: "medium",
  },
  {
    text: "The mass of men lead lives of quiet desperation. What is called resignation is confirmed desperation. From the desperate city you go into the desperate country, and have to console yourself with the bravery of minks and muskrats.",
    author: "Henry David Thoreau",
    length: "medium",
  },
  {
    text: "If you want to build a ship, do not drum up people to collect wood and do not assign them tasks and work, but rather teach them to long for the endless immensity of the sea.",
    author: "Antoine de Saint-Exupery",
    length: "medium",
  },
  {
    text: "Perfection is attained not when there is no longer anything to add, but when there is no longer anything to take away. It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
    author: "Antoine de Saint-Exupery",
    length: "medium",
  },
  {
    text: "The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly. A programmer is ideally an essayist who works with traditional aesthetic and literary forms.",
    author: "Donald Knuth",
    length: "medium",
  },
  {
    text: "Premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical three percent, and a good programmer will not be lulled into complacency by such reasoning either.",
    author: "Donald Knuth",
    length: "medium",
  },
  {
    text: "Everybody in this country should learn to program a computer, because it teaches you how to think. I think everybody should have a computer, and everybody should learn to use it, and nobody should be afraid of it.",
    author: "Steve Jobs",
    length: "medium",
  },
  {
    text: "Innovation distinguishes between a leader and a follower. Your time is limited, so do not waste it living someone else's life. Do not let the noise of others' opinions drown out your own inner voice.",
    author: "Steve Jobs",
    length: "medium",
  },
  {
    text: "Simple can be harder than complex. You have to work hard to get your thinking clean to make it simple, but it is worth it in the end because once you get there, you can move mountains.",
    author: "Steve Jobs",
    length: "medium",
  },
  {
    text: "The best way to predict the future is to invent it. Technology is anything that was not around when you were born, and the real problem is that people confuse the medium with the message it carries.",
    author: "Alan Kay",
    length: "medium",
  },
  {
    text: "Most software today is very much like an Egyptian pyramid, with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.",
    author: "Alan Kay",
    length: "medium",
  },
  {
    text: "Point of view is worth eighty IQ points. A change in perspective can dissolve a problem that has resisted every clever technique you could throw at it, which is why the best debugging tool is a good night of sleep.",
    author: "Alan Kay",
    length: "medium",
  },
  {
    text: "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning.",
    author: "Rick Cook",
    length: "medium",
  },
  {
    text: "The trouble with programmers is that you can never tell what a programmer is doing until it is too late. Adding manpower to a late software project makes it later, and nine women cannot make a baby in one month.",
    author: "Fred Brooks",
    length: "medium",
  },
  {
    text: "Plan to throw one away, you will anyhow. The hardest single part of building a software system is deciding precisely what to build, and no other part of the work so cripples the result if done wrong.",
    author: "Fred Brooks",
    length: "medium",
  },
  {
    text: "Show me your flowcharts and conceal your tables, and I shall continue to be mystified. Show me your tables, and I will not usually need your flowcharts; they will be obvious.",
    author: "Fred Brooks",
    length: "medium",
  },
  {
    text: "What one programmer can do in one month, two programmers can do in two months. Nothing is harder to schedule than the moment a hard problem finally makes sense, and no manager has ever found a way to buy it.",
    author: "Fred Brooks",
    length: "medium",
  },
  {
    text: "The competent programmer is fully aware of the strictly limited size of his own skull. He therefore approaches the programming task in full humility, and among other things he avoids clever tricks like the plague. It is not the machine that must be respected but the reader who comes after, carrying no memory of why any of it was written the way it was.",
    author: "Edsger Dijkstra",
    length: "long",
  },
  {
    text: "Simplicity is a great virtue but it requires hard work to achieve it and education to appreciate it. And to make matters worse, complexity sells better. The market rewards the appearance of power, and only the person who has to maintain the thing for five years ever learns what the appearance actually cost.",
    author: "Edsger Dijkstra",
    length: "long",
  },
  {
    text: "If you want more effective programmers, you will discover that they should not waste their time debugging, they should not introduce the bugs to start with. Program testing can be a very effective way to show the presence of bugs, but it is hopelessly inadequate for showing their absence.",
    author: "Edsger Dijkstra",
    length: "long",
  },
  {
    text: "The tools we use have a profound and devious influence on our thinking habits, and therefore on our thinking abilities. A programming language is a tool, but it is also a way of seeing, and the shape of what you can easily say determines the shape of what you will usually think.",
    author: "Edsger Dijkstra",
    length: "long",
  },
  {
    text: "Everyone knows that debugging is twice as hard as writing a program in the first place. So if you are as clever as you can be when you write it, how will you ever debug it? The answer is that you will not, and this is why the cleverest line in a program is almost always the one that eventually costs the most.",
    author: "Brian Kernighan",
    length: "long",
  },
  {
    text: "Do not comment bad code, rewrite it. Make it clear before you make it faster, and do not sacrifice clarity for small gains in efficiency. Write clearly, do not be too clever, say what you mean simply and directly, and let the machine do the dull work of making it fast enough for the people who will use it.",
    author: "Brian Kernighan",
    length: "long",
  },
  {
    text: "It is far better to have an approximate answer to the right question, which is often vague, than an exact answer to the wrong question, which can always be made precise. In every field the hard part is not the arithmetic; it is deciding which arithmetic is worth doing at all.",
    author: "John Tukey",
    length: "long",
  },
  {
    text: "The purpose of abstraction is not to be vague, but to create a new semantic level in which one can be absolutely precise. A good abstraction is not a place to hide from detail; it is a place where the detail has been organized so completely that you can reason about a hundred cases at once without losing any of them.",
    author: "Edsger Dijkstra",
    length: "long",
  },
  {
    text: "Machines take me by surprise with great frequency. This is largely because I do not do sufficient calculation to decide what to expect them to do, or rather because, although I do a calculation, I do it in a hurried and slipshod fashion. We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    author: "Alan Turing",
    length: "long",
  },
  {
    text: "I believe that at the end of the century the use of words and general educated opinion will have altered so much that one will be able to speak of machines thinking without expecting to be contradicted. Instead of trying to produce a program to simulate the adult mind, why not rather try to produce one which simulates the child's?",
    author: "Alan Turing",
    length: "long",
  },
  {
    text: "A computer would deserve to be called intelligent if it could deceive a human into believing that it was human. The original question, can machines think, I believe to be too meaningless to deserve discussion, and yet it has occupied more clever people than almost any other question of its century.",
    author: "Alan Turing",
    length: "long",
  },
  {
    text: "The Analytical Engine has no pretensions whatever to originate anything. It can do whatever we know how to order it to perform. It can follow analysis, but it has no power of anticipating any analytical relations or truths. Its province is to assist us in making available what we are already acquainted with.",
    author: "Ada Lovelace",
    length: "long",
  },
  {
    text: "That brain of mine is something more than merely mortal, as time will show. I never am really satisfied that I understand anything, because, understand it well as I may, my comprehension can only be an infinitesimal fraction of all I want to understand about the many connections and relations which occur to me.",
    author: "Ada Lovelace",
    length: "long",
  },
  {
    text: "It is a capital mistake to theorize before one has data. Insensibly one begins to twist facts to suit theories, instead of theories to suit facts. The temptation to form premature theories upon insufficient data is the bane of our profession, and the one habit that separates the careful worker from the merely confident one.",
    author: "Arthur Conan Doyle",
    length: "long",
  },
  {
    text: "When you have eliminated the impossible, whatever remains, however improbable, must be the truth. The world is full of obvious things which nobody by any chance ever observes, and there is nothing more deceptive than an obvious fact, which is why the plainest cases are so often the hardest ones to see clearly.",
    author: "Arthur Conan Doyle",
    length: "long",
  },
  {
    text: "The scientist is not a person who gives the right answers, he is one who asks the right questions. Knowledge is not a collection of settled facts to be handed down but a running argument, conducted carefully, in which being wrong in public is not a disgrace but the entire mechanism by which anything improves.",
    author: "Claude Levi-Strauss",
    length: "long",
  },
  {
    text: "Somewhere in the world there is a person who has already solved the problem you are stuck on, and who wrote it down, and whose writing you have not found yet. The whole discipline of research is a long practice in the humility of looking before building, and in the patience of reading what looks unpromising.",
    author: "Unknown",
    length: "long",
  },
  {
    text: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of light, it was the season of darkness, it was the spring of hope, it was the winter of despair.",
    author: "Charles Dickens",
    length: "long",
  },
  {
    text: "Happy families are all alike; every unhappy family is unhappy in its own way. Everything was in confusion in the house, and the wife had discovered that the husband was carrying on an intrigue with a governess, and she had announced that she could not go on living in the same house with him.",
    author: "Leo Tolstoy",
    length: "long",
  },
  {
    text: "In my younger and more vulnerable years my father gave me some advice that I have been turning over in my mind ever since. Whenever you feel like criticizing anyone, he told me, just remember that all the people in this world have not had the advantages that you have had, and reserve your judgment accordingly.",
    author: "F. Scott Fitzgerald",
    length: "long",
  },
  {
    text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families that he is considered as the rightful property of some one of their daughters.",
    author: "Jane Austen",
    length: "long",
  },
  {
    text: "All happy endings begin with somebody deciding to keep going on an ordinary morning when nothing in particular has changed. The world is not moved only by the mighty shoves of its heroes but also by the tiny pushes of each honest worker, and it is the accumulation of those that finally turns the wheel.",
    author: "Helen Keller",
    length: "long",
  },
  {
    text: "I do not know what I may appear to the world, but to myself I seem to have been only like a boy playing on the seashore, and diverting myself in now and then finding a smoother pebble or a prettier shell than ordinary, whilst the great ocean of truth lay all undiscovered before me.",
    author: "Isaac Newton",
    length: "long",
  },
  {
    text: "The important thing is not to stop questioning. Curiosity has its own reason for existing. One cannot help but be in awe when he contemplates the mysteries of eternity, of life, of the marvelous structure of reality. It is enough if one tries merely to comprehend a little of this mystery every day.",
    author: "Albert Einstein",
    length: "long",
  },
  {
    text: "Look deep into nature, and then you will understand everything better. The most beautiful experience we can have is the mysterious; it is the fundamental emotion which stands at the cradle of true art and true science, and whoever does not know it can no longer wonder and is as good as dead.",
    author: "Albert Einstein",
    length: "long",
  },
  {
    text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. I am among those who think that science has great beauty, and a scientist in a laboratory is not only a technician but also a child placed before natural phenomena which impress like a fairy tale.",
    author: "Marie Curie",
    length: "long",
  },
  {
    text: "We cannot solve our problems with the same thinking we used when we created them. The world as we have created it is a process of our thinking, and it cannot be changed without changing our thinking, which is a far slower and far more uncomfortable operation than anyone ever budgets time for.",
    author: "Albert Einstein",
    length: "long",
  },
  {
    text: "There is a crack in everything, that is how the light gets in. Nothing is ever finished, nothing is ever perfect, and the parts of a system that show their seams most plainly are often the parts that have been honest enough about their limits for someone else to build on top of them.",
    author: "Leonard Cohen",
    length: "long",
  },
  {
    text: "The best moment in the writing process is when the thing you have made stops arguing with you and starts arguing with the world instead. Until then every sentence is a negotiation, and the only way through it is to keep putting down words that are worse than the ones you wanted and then fixing them tomorrow.",
    author: "Unknown",
    length: "long",
  },
  {
    text: "Everything you have ever wanted is on the other side of a long stretch of work that nobody will see and that will not feel meaningful while you are doing it. The gap between the taste that made you start and the skill that will satisfy you is closed by volume, by finishing things, and by nothing else.",
    author: "Ira Glass",
    length: "long",
  },
];

/** Cheap seeded shuffle-free random pick. */
function pick<T>(items: readonly T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

/** Random words, never repeating the immediately previous word. */
export function generateWords(count: number): string[] {
  const out: string[] = [];
  let previous = "";
  for (let i = 0; i < count; i++) {
    let word = pick(WORD_BANK);
    let guard = 0;
    while (word === previous && guard++ < 8) word = pick(WORD_BANK);
    out.push(word);
    previous = word;
  }
  return out;
}

export function randomQuote(length: QuoteLength): Quote {
  const pool = QUOTES.filter((q) => q.length === length);
  return pick(pool.length > 0 ? pool : QUOTES);
}

/** Split a quote into typeable word tokens (punctuation stays attached). */
export function quoteToWords(quote: Quote): string[] {
  return quote.text.trim().split(/\s+/);
}
